services:
    sonata.admin.meal:
        class: Mamidi\ClassifiedBundle\Admin\MealAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Meal" }
        arguments:
            - ~
            - Mamidi\ClassifiedBundle\Entity\Meal
            - ~
        calls:
            - [ setTranslationDomain, [ClassifiedBundle]]