host_reservations:
    path:     /reservations/
    defaults: { _controller: MamidiClassifiedBundle:Reservation:index }

accept:
    path:     /accept
    defaults: { _controller: MamidiClassifiedBundle:Reservation:accept }

reject:
    path:     /reject
    defaults: { _controller: MamidiClassifiedBundle:Reservation:reject }
