host_registration:
    pattern:  /register/host
    defaults: { _controller: MamidiUserBundle:HostRegistration:register }

guest_registration:
    pattern:  /register/guest
    defaults: { _controller: MamidiUserBundle:GuestRegistration:register }

mamidi_host_homepage:
    path:     /host/{name}
    defaults: { _controller: MamidiUserBundle:Default:index }

mamidi_guest_homepage:
    path:     /guest/{name}
    defaults: { _controller: MamidiUserBundle:Default:index }

mamidi_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MamidiUserBundle:Default:index }

host_meals:
    path:     /{host}/meals
    defaults: { _controller: MamidiUserBundle:Host:meals }
