host_registration:
    pattern:  /register/host
    defaults: { _controller: MamidiUserBundle:HostRegistration:register }

guest_registration:
    pattern:  /register/guest
    defaults: { _controller: MamidiUserBundle:GuestRegistration:register }

mamidi_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: MamidiUserBundle:Default:index }
